### ISSUE TITLE
React way

### ISSUE THREAD

**Issue by Alaev** [react-u/18-infinite-scrolling-using-react#1]
Hey first great job on the view and helping people learn for free,

I need to point out that you are doing things not the "react" way.
For example, The line below you are selecting DOM element out side of React.
The right way is to select it via ["Ref"](https://reactjs.org/docs/glossary.html#refs) within React itself.

https://github.com/react-u/18-infinite-scrolling-using-react/blob/906f9c5315566e9fd6bd53a4e49b600f739138ce/src/features/contact-list/index.js#L25

Also, you did use some methods from React lifecycle that are a bit unsafe to use as of react 16.3 like `componentWillMount` 
https://github.com/react-u/18-infinite-scrolling-using-react/blob/906f9c5315566e9fd6bd53a4e49b600f739138ce/src/features/contact-list/index.js#L14

Great job over all.

**Comment by marktellez** [comment]
Yeah, about the componentwillmount - it sort of breaks my heart that will and did mount are being removed at some point. they havent really addressed the replacement, or did I miss something?

**Comment by Alaev** [comment]
@marktellez 

I think the right solution is to use `componentDidMount()` to add loading indication if you are getting data from a server. Also, you can look at [getSnapshotBeforeUpdate()](https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate)

`getSnapshotBeforeUpdate()` is invoked right before the most recently rendered output is committed to e.g. the DOM. It enables your component to capture current values (e.g. scroll position) before they are potentially changed. Any value returned by this lifecycle will be passed as a parameter to `componentDidUpdate().`
